#!/bin/sh
# Regenerates the "Pinned Versions" table in README.md from the files that
# actually define those versions.
#
# Dependabot can only edit manifests (go.mod, Dockerfile, workflow `uses:`), so
# a hand-maintained table in the README silently goes stale after every bot PR.
# This script is the single source of truth instead, and CI runs it with
# `--check` so a drifting README fails the build rather than being merged.
#
#   ./scripts/sync-readme-versions.sh          rewrite README.md in place
#   ./scripts/sync-readme-versions.sh --check   exit 1 if README.md is stale
set -eu

cd "$(dirname "$0")/.."

README=README.md
START='<!-- versions:start -->'
END='<!-- versions:end -->'

fail() { echo "error: $*" >&2; exit 1; }

# --- collect the actual versions ------------------------------------------
go_min=$(awk '/^go /{print $2; exit}' go.mod)
go_toolchain=$(sed -n 's/^FROM golang:\([0-9][0-9.]*\)-alpine.*/\1/p' Dockerfile | head -1)
alpine=$(sed -n 's/^FROM alpine:\([0-9][0-9.]*\).*/\1/p' Dockerfile | head -1)
terraform=$(sed -n 's|.*hashicorp/terraform:\([0-9][0-9.]*\).*|\1|p' Dockerfile | head -1)

mod_version() {
	awk -v m="$1" '$1 == m { print $2; exit }' go.mod
}
framework=$(mod_version github.com/hashicorp/terraform-plugin-framework)
validators=$(mod_version github.com/hashicorp/terraform-plugin-framework-validators)
testing=$(mod_version github.com/hashicorp/terraform-plugin-testing)

for pair in "go_min:$go_min" "go_toolchain:$go_toolchain" "alpine:$alpine" \
	"terraform:$terraform" "framework:$framework" "validators:$validators" \
	"testing:$testing"; do
	name=${pair%%:*}
	value=${pair#*:}
	[ -n "$value" ] || fail "could not determine $name"
done

# --- the toolchain is pinned in more places than the table can show ---------
# The README names one Go toolchain, so every copy has to agree with the
# Dockerfile. Dependabot only bumps the Dockerfile; this catches the rest.
mismatch=
for v in $(sed -n 's/^FROM golang:\([0-9][0-9.]*\)-alpine.*/\1/p' Dockerfile); do
	[ "$v" = "$go_toolchain" ] || mismatch="$mismatch
  Dockerfile: golang:$v"
done
for f in .github/workflows/*.yml; do
	for v in $(sed -n \
		-e "s/^ *GO_VERSION: *'\{0,1\}\([0-9][0-9.]*\)'\{0,1\} *$/\1/p" \
		-e "s/^ *go-version: *'\{0,1\}\([0-9][0-9.]*\)'\{0,1\} *$/\1/p" "$f"); do
		[ "$v" = "$go_toolchain" ] || mismatch="$mismatch
  $f: $v"
	done
done
make_go=$(sed -n 's/^GO_VERSION := *//p' Makefile)
[ "$make_go" = "$go_toolchain" ] || mismatch="$mismatch
  Makefile: GO_VERSION := $make_go"
[ -z "$mismatch" ] || fail "Go toolchain is $go_toolchain in the Dockerfile builder, but:$mismatch"

# --- render the table ------------------------------------------------------
table=$(cat <<EOF
$START
<!-- Generated by scripts/sync-readme-versions.sh - do not edit by hand. -->

| Component | Version | Defined in |
|-----------|---------|------------|
| Go (toolchain used to build and test) | $go_toolchain | \`Dockerfile\`, \`.github/workflows/\` |
| Go (minimum required) | $go_min | \`go.mod\` |
| Terraform CLI (acceptance tests) | $terraform | \`Dockerfile\` |
| Alpine (runtime image) | $alpine | \`Dockerfile\` |
| terraform-plugin-framework | $framework | \`go.mod\` |
| terraform-plugin-framework-validators | $validators | \`go.mod\` |
| terraform-plugin-testing | $testing | \`go.mod\` |
$END
EOF
)

grep -qF "$START" "$README" || fail "$README has no $START marker"
grep -qF "$END" "$README" || fail "$README has no $END marker"

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

awk -v start="$START" -v end="$END" -v table="$table" '
	index($0, start) { print table; skip = 1; next }
	index($0, end)   { skip = 0; next }
	!skip            { print }
' "$README" > "$tmp"

if [ "${1:-}" = "--check" ]; then
	if cmp -s "$tmp" "$README"; then
		echo "README.md version table is up to date."
		exit 0
	fi
	echo "README.md version table is out of date. Diff:" >&2
	diff -u "$README" "$tmp" >&2 || true
	echo >&2
	echo "Run ./scripts/sync-readme-versions.sh (or 'make docs') and commit the result." >&2
	exit 1
fi

cat "$tmp" > "$README"
echo "README.md version table updated."
